Employees/Models/Employee.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace Employees.Models
{
	public class Employee
	{
		public int Id { get; set; }

		public string? UserName { get; set; }

        public string? Department { get; set; }

		public DateTime? BirthDate { get; set; }

		public DateTime? DateOfEmployment { get; set; }

		public double? Wage { get; set; }
	}
}

Employees/Models/ErrorViewModel.cs
namespace Employees.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Employees/Controllers/EmployesController.cs
using System;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Data;
using Employees.Services.Interface;
using Employees.Models;

namespace Employes.Controllers
{
	public class EmployesControler : Controller
	{
        private readonly IEmployeesRepository _employeesRepository;

        public EmployesControler(IEmployeesRepository employeesRepository)
        {
            _employeesRepository = employeesRepository;
        }

        public async Task<IActionResult> Index()
        {
            var products = await _employeesRepository.GetAllEmployees();
            return View(products);
        }

        public async Task<IActionResult> Details(int id)
        {
            if (id == null) return NotFound();

            var product = await _employeesRepository.GetEmployeeIdAsync(id);
            if (product == null) return NotFound();

            return View(product);
        }

        public IActionResult Create() => View();


        [HttpPost]

        public async Task<IActionResult> Create([Bind("Id,Title,Quantity,Price")] Employee employee)
        {
            if (!ModelState.IsValid) return View(employee);
            await _employeesRepository.CreateEmployeeAsync(employee);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Edit(int id)
        {
            if (id == null) return NotFound();

            var product = await _employeesRepository.GetEmployeeIdAsync(id);
            if (product == null) return NotFound();

            return View(product);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Quantity,Price")] Employee employee)
        {
            if (id != employee.Id) return NotFound();

            if (!ModelState.IsValid) return View(employee);

            try
            {
                var newProduct = await _employeesRepository.UpdateEmployeeAsync(employee);
            }
            catch (DbUpdateConcurrencyException)
            {
                if (_employeesRepository.GetEmployeeIdAsync(employee.Id) == null)
                    return NotFound();
                else
                    throw;
            }
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int id)
        {
            if (id == null) return NotFound();

            var product = await _employeesRepository.GetEmployeeIdAsync(id);

            if (product == null) return NotFound();

            return View(product);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var product = await _employeesRepository.DeleteEmployeeAsync(id);
            if (product == null) return NotFound();
            return RedirectToAction(nameof(Index));
        }
    }
}

Employees/Controllers/EmploysController.cs
using System;
using Employees.FluentValidation;
using Employees.Models;
using Employees.Services.Interface;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Employees.Controllers
{
    public class EmploysController : Controller
    {
        private readonly IEmployeesRepository _employeesRepository;

        public EmploysController(IEmployeesRepository employeesRepository)
        {
            
            _employeesRepository = employeesRepository;
        }
        public async Task<IActionResult> Index()
        {
            var products = await _employeesRepository.GetAllEmployees();
            return View(products);
        }


        public IActionResult Create() => View();


        [HttpPost]
        public async Task<IActionResult> Create(Employee employee)
        {
            var validationResult = await new EmploysModelValidation().ValidateAsync(employee);

            if (!validationResult.IsValid)
            {
                foreach (var error in validationResult.Errors)
                {
                    ModelState.AddModelError(error.PropertyName, error.ErrorMessage);
                }

                return View(employee);
            }
            if (!ModelState.IsValid) return View(employee);
            Employee employee1 = new Employee
            {
                UserName = employee.UserName,
                Department = employee.Department,
                BirthDate = employee.BirthDate?.ToUniversalTime(),
                DateOfEmployment = employee.DateOfEmployment?.ToUniversalTime(),
                Wage = employee.Wage
            };
            await _employeesRepository.CreateEmployeeAsync(employee1);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Edit(int id)
        {
            if (id == null) return NotFound();
            var product = await _employeesRepository.GetEmployeeIdAsync(id);
            if (product == null) return NotFound();
            return View(product);
        }

        [HttpPost]
        public async Task<IActionResult> Edit( Employee employee)
        {
            //if (id != employee.Id) return NotFound();

            if (!ModelState.IsValid) return View(employee);

            try
            {
                Employee employee1 = new Employee
                {
                    UserName = employee.UserName,
                    Department = employee.Department,
                    BirthDate = employee.BirthDate?.ToUniversalTime(),
                    DateOfEmployment = employee.DateOfEmployment?.ToUniversalTime(),
                    Wage = employee.Wage
                };
                var newProduct = await _employeesRepository.UpdateEmployeeAsync(employee1);
            }
            catch (DbUpdateConcurrencyException)
            {
                if (_employeesRepository.GetEmployeeIdAsync(employee.Id) == null)
                    return NotFound();
                else
                    throw;
            }
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int id)
        {
            if (id == null) return NotFound();

            var product = await _employeesRepository.GetEmployeeIdAsync(id);

            if (product == null) return NotFound();

            return View(product);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var product = await _employeesRepository.DeleteEmployeeAsync(id);
            if (product == null) return NotFound();
            return RedirectToAction(nameof(Index));
        }
    }
}

Employees/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Employees.Models;

namespace Employees.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Employees/Views/Employes/Create.cshtml
@model Employees.Models.Employee

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Product</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="UserName" class="control-label"></label>
                <input asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BirthDate" class="control-label"></label>
                <input asp-for="BirthDate" class="form-control" />
                <span asp-validation-for="BirthDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Wage" class="control-label"></label>
                <input asp-for="Wage" class="form-control" />
                <span asp-validation-for="Wage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Employees/Views/Employes/Delete.cshtml
@model Employees.Models.Employee

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Product</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.UserName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.UserName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.BirthDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.BirthDate)
        </dt>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Wage)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Wage)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Employees/Views/Employes/Details.cshtml
@model Employees.Models.Employee

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Product</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.UserName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.UserName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.BirthDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.BirthDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Wage)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Wage)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Employees/Views/Employes/Edit.cshtml
@model Employees.Models.Employee

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Product</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="UserName" class="control-label"></label>
                <input asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BirthDate" class="control-label"></label>
                <input asp-for="BirthDate" class="form-control" />
                <span asp-validation-for="BirthDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Wage" class="control-label"></label>
                <input asp-for="Wage" class="form-control" />
                <span asp-validation-for="Wage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Employees/Views/Employes/Index.cshtml
@model IEnumerable<Employees.Models.Employee>

<h1>Products</h1>


<a asp-action="Create" asp-controller="Employes" class="btn btn-primary">Create New</a>


<table class="table  table-bordered table-hover">
    <thead class="thead-dark">
        <tr>
            <th scope="col">
                @Html.DisplayNameFor(model => model.UserName)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.BirthDate)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.Wage)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.UserName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BirthDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Wage)
                </td>

                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-info">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-secondary">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">Delete</a> |
                </td>

            </tr>
        }
    </tbody>
</table>

Employees/Views/Employs/Create.cshtml
@model Employees.Models.Employee

@{
    ViewData["Title"] = "Create";
}

<h1>Create Employee</h1>

<form asp-action="Create" asp-controller="Employs">
    <div>
        <label asp-for="UserName">Username:</label>
        <input asp-for="UserName" class="form-control" />
        <span asp-validation-for="UserName" class="text-danger"></span>
    </div>

    <div>
        <label asp-for="Department">Department:</label>
        <input asp-for="Department" class="form-control" />
        <span asp-validation-for="Department" class="text-danger"></span>
    </div>

    <div>
        <label asp-for="BirthDate">Birth Date:</label>
        <input asp-for="BirthDate" type="date" class="form-control" />
        <span asp-validation-for="BirthDate" class="text-danger"></span>
    </div>

    <div>
        <label asp-for="DateOfEmployment">Date of Employment:</label>
        <input asp-for="DateOfEmployment" type="date" class="form-control" />
        <span asp-validation-for="DateOfEmployment" class="text-danger"></span>
    </div>

    <div>
        <label asp-for="Wage">Wage:</label>
        <input asp-for="Wage" type="number" class="form-control" />
        <span asp-validation-for="Wage" class="text-danger"></span>
    </div>

    <div>
        <input type="submit" value="Create" class="btn btn-primary mt-4" />
    </div>
</form>
<script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.5.1.min.js"></script>
<script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.17.0/jquery.validate.min.js"></script>
<script src="https://ajax.aspnetcdn.com/ajax/jquery.validation.unobtrusive/3.2.10/jquery.validate.unobtrusive.min.js"></script>

Employees/Views/Employs/Delete.cshtml
@model Employees.Models.Employee

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Product</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.UserName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.UserName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.BirthDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.BirthDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Wage)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Wage)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Department)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Department)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DateOfEmployment)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DateOfEmployment)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Employees/Views/Employs/Details.cshtml
@model Employees.Models.Employee

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Product</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.UserName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.UserName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.BirthDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.BirthDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Wage)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Wage)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Employees/Views/Employs/Edit.cshtml
@model Employees.Models.Employee

@{
    ViewData["Title"] = "Create";
}

<h1>Create Employee</h1>

<form asp-action="Edit" asp-controller="Employs">
    <div>
        <label asp-for="UserName">Username:</label>
        <input asp-for="UserName" class="form-control" />
        <span asp-validation-for="UserName" class="text-danger"></span>
    </div>

    <div>
        <label asp-for="Department">Department:</label>
        <input asp-for="Department" class="form-control" />
        <span asp-validation-for="Department" class="text-danger"></span>
    </div>

    <div>
        <label asp-for="BirthDate">Birth Date:</label>
        <input asp-for="BirthDate" type="date" class="form-control" />
        <span asp-validation-for="BirthDate" class="text-danger"></span>
    </div>

    <div>
        <label asp-for="DateOfEmployment">Date of Employment:</label>
        <input asp-for="DateOfEmployment" type="date" class="form-control" />
        <span asp-validation-for="DateOfEmployment" class="text-danger"></span>
    </div>

    <div>
        <label asp-for="Wage">Wage:</label>
        <input asp-for="Wage" type="number" class="form-control" />
        <span asp-validation-for="Wage" class="text-danger"></span>
    </div>

    <div>
        <input type="submit" value="Update" class="btn btn-primary mt-4" />
    </div>
</form>
<script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.5.1.min.js"></script>
<script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.17.0/jquery.validate.min.js"></script>
<script src="https://ajax.aspnetcdn.com/ajax/jquery.validation.unobtrusive/3.2.10/jquery.validate.unobtrusive.min.js"></script>

Employees/Views/Employs/Index.cshtml
@model IEnumerable<Employees.Models.Employee>

<h1>Products</h1>


<a asp-action="Create" asp-controller="Employs" class="btn btn-primary">Create New</a>


<table class="table  table-bordered table-hover">
    <thead class="thead-dark">
        <tr>
            <th scope="col">
                @Html.DisplayNameFor(model => model.UserName)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.BirthDate)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.Department)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.DateOfEmployment)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.Wage)
            </th>
            <th scope="col">
             Details
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.UserName)
                </td>
                <td>@CalculateAge(item.BirthDate)</td>

                <td>
                    @Html.DisplayFor(modelItem => item.Department)
                </td>

                <td>@item.BirthDate?.ToString("dd.MM.yyyy")</td>

                <td>
                    @Html.DisplayFor(modelItem => item.Wage)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-info">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-secondary">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">Delete</a> |
                </td>

            </tr>
        }
    </tbody>
</table>
@functions {
    private string CalculateAge(DateTime? dateOfBirth)
    {
        if (dateOfBirth.HasValue)
        {
            var today = DateTime.Today;
            var age = today.Year - dateOfBirth.Value.Year;

            if (today.Month < dateOfBirth.Value.Month || (today.Month == dateOfBirth.Value.Month && today.Day < dateOfBirth.Value.Day))
            {
                age--;
            }

            return age.ToString();
        }

        return "N/A";
    }
}

Employees/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Employees/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Employees</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Employees.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Employees</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Employs" asp-action="Index">EMPLOYEES</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Employees - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>